services:
  node:
    image: node:20-slim
    container_name: node
    working_dir: /app
    user: node
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development

networks:
  app-network:
    driver: bridge
